FROM node:20-alpine

WORKDIR /app

# Install dependencies only when needed
COPY package.json ./
RUN npm install --legacy-peer-deps

# Copy rest of the files
COPY . .

# Expose development port
EXPOSE 3001

# Start development server
CMD ["npm", "run", "dev"]